### ISSUE TITLE
✅ Ruby Catalog of items - Kanban Board Setup 🎫 #22

### ISSUE THREAD

**Issue by maximoortelli** [fmanimashaun/catalog_of_items#37]
### Hi there! We are @fmanimashaun  and @maximoortelli 
------------------------------------------------------------------------------------------------------------------------------------------------------

- Team Member 1: @fmanimashaun 
- Team Member 2: @maximoortelli 

✅ [Ruby Project Kanban Board](https://github.com/users/fmanimashaun/projects/11)

**Comment by julie-ify** [comment]
Hi @maximoortelli and @fmanimashaun,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly specify the link to the kanban project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by julie-ify** [comment]
## Hi @maximoortelli and @fmanimashaun,

Good job so far!

## Highlights!
- Good column organization and task assignment ✔️
- Descriptive issue ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] There should only be four columns namely: To do, In Progress, In Review and Done. Kindly remove the No status column. Tasks should start from the To do column.

  ![image](https://github.com/fmanimashaun/catalog_of_items/assets/81468675/b520eb2a-65ec-4e66-8d53-f86f7fb89842)

- [ ] You appear to have condensed the numerous tasks into only about 7 issues. Kindly note that each itemized task listed in the requirements should have a distinct issue for it and should have appropriate description. This is important for providing enough context for an issue.

  ![image](https://github.com/fmanimashaun/catalog_of_items/assets/81468675/29ae3c93-7f2f-4b81-bbde-62fb0ed89c5d)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
